spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessActivity
      database: fitnessActivity
  application:
    name: activity-service
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
