server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fitnessActivity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
