server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ai-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: fitness_ai

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue

claude:
  api:
    key: ${CLAUDE_API_KEY}
    url: https://api.anthropic.com/v1/messages
    model: claude-3-sonnet-20240229

logging:
  level:
    com.fitness.aiservice: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.data.mongodb: INFO

spring.jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false
  date-format: yyyy-MM-dd'T'HH:mm:ss
  time-zone: UTC
