server:
  port: 8084

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_ai

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

claude:
  api:
    key: ${CLAUDE_API_KEY:default-key}

logging:
  level:
    com.fitness.aiservice: DEBUG
    org.springframework.web: INFO
