spring:
  application:
    name:userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_users_db
    password: jayshah18.
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL

