spring:
  application:
    name:userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user_db
    password: postgres
    username: jayshah18.

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL

